problem_data.o: problem_data.h problem_data.cpp
	$(CXX) $(CPPFLAGS) -c -o problem_data.o
	
program_params.o: program_params.h program_params.cpp
	$(CXX) $(CPPFLAGS) -c -o program_params.o

graph_generator.o: graph_generator.h graph_generator.cpp
	$(CXX) $(CPPFLAGS) -c -o graph_generator.o