bb_node.o: bb_node.h bb_node.cpp
	$(CXX) $(CPPFLAGS) -c -o bb_node.o
	
bb_tree.o: bb_tree.h bb_tree.cpp
	$(CXX) $(CPPFLAGS) -c -o bb_tree.o

cycle.o: cycle.h cycle.cpp
	$(CXX) $(CPPFLAGS) -c -o cycle.o