node.o: node.h port.h vessel_class.h node.cpp
	$(CXX) $(CPPFLAGS) -c -o node.o

graph.o: arc.h graph.h graph.cpp
	$(CXX) $(CPPFLAGS) -c -o graph.o
	
problem.o: problem.h problem.cpp
	$(CXX) $(CPPFLAGS) -c -o problem.o