labelling.o: id_maps.h labelling.h labelling.cpp
	$(CXX) $(CPPFLAGS) -c -o labelling.o

heuristics_solver.o: heuristics_solver.h heuristics_solver.cpp
	$(CXX) $(CPPFLAGS) -c -o heuristics_solver.o
	
exact_solver.o: exact_solver.h exact_solver.cpp
	$(CXX) $(CPPFLAGS) -c -o exact_solver.o
	
sp_solver.o: sp_solver.h sp_solver.cpp
	$(CXX) $(CPPFLAGS) -c -o sp_solver.o

threaded_solver.o: threaded_solver.h threaded_solver.cpp
	$(CXX) $(CPPFLAGS) -c -o threaded_solver.o